#numpy

In [2]:
import numpy as np

In [5]:
m=np.array([1,7])
m

array([1, 7])

In [10]:
m=np.array([[1,2,2],[3,4,5]])
m.shape

[[1 2 2]
 [3 4 5]]


(2, 3)

In [14]:
n=np.arange(1,30,2)
print(n)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


In [24]:
print(np.reshape(m,(1,6)))

[[1 2 2 3 4 5]]


In [23]:
print(np.resize(m,(2,4)))

[[1 2 2 3]
 [4 5 1 2]]


In [28]:
o=np.linspace(0,4,9)
o.resize(2,3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5]])

In [34]:
np.eye(3)
np.diag((2,3,4))

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [35]:
np.vstack([m,m*2]) #np.hstack([m,m*2])

array([[ 1,  2,  2],
       [ 3,  4,  5],
       [ 2,  4,  4],
       [ 6,  8, 10]])

In [36]:
m.T #transfer

array([[1, 3],
       [2, 4],
       [2, 5]])

In [45]:
m[-1,(0,1)]

array([3, 4])

In [50]:
m[0:1,0:1]

array([[1]])

In [47]:
m

array([[1, 2, 2],
       [3, 4, 5]])

#pandas

In [2]:
import pandas as pd

In [68]:
animals=['tiger','moose','seal']
pd.Series(animals)
a=pd.Series(['tiger','moose','seal'],index=['a','b','c'])
a.iloc[1]  #moose
a.loc['a'] #tiger 
a[1] #moose
#loc works on index, iloc works on position

'moose'

In [35]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])

In [5]:
df['Name'][df['Cost']>3]
df['Name'].where(df['Cost']>3)  return NaN
df['store']=df.index
df=df.set_index('Name')
df=df.reset_index()
df['location']=df.index
df=df.set_index(['location','Name'])
df = df.append(pd.Series(data={'Cost': 3.00, 'Item Purchased': 'Kitty Food'}, name=('Store 2', 'Kevyn')))
df.loc[df['Cost']==df['Cost'].max()]


Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris

In [59]:
df['cost2']=8
df['hh']=df[['Cost','cost2']].min(axis=1) 
a=[1,2]
df['Name'][[1,2]]

Store 1    Kevyn
Store 2    Vinod
Name: Name, dtype: object

In [16]:
df.index[df['Cost']>3]

Index(['Store 1', 'Store 2'], dtype='object')

In [73]:
x=[1,1,2,4]
set(x)

{1, 2, 4}

In [25]:
df.fillna?

In [93]:
df['Name'].str.startswith('C')

Store 1     True
Store 1    False
Store 2    False
Name: Name, dtype: bool

In [ ]:
pd.merge(student_df,staff_df,how='outer',left_index=True, right_index='Name') #how='inner','right','left'

In [ ]:
pd.merge(student_df,staff_df,how='outer',left_on=['Last Name','First Name'],right_on=['Last Name','First Name'])

In [6]:
df = df.rename(columns={'oldname': 'newname', 'Item Purchased': 'item'})
#df.columns=['cost','item','name']

In [40]:
df=df.drop(df[df['Cost']==5.0].index)
df

In [42]:
s = pd.Series(['Low', 'Low', 'High', 'Medium', 'Low', 'High', 'Low'])
s.astype('category', categories=['Low', 'Medium', 'High'],ordered=True)

0       Low
1       Low
2      High
3    Medium
4       Low
5      High
6       Low
dtype: category
Categories (3, object): [Low < Medium < High]

In [ ]:
s = pd.Series([168, 180, 174, 190, 170, 185, 179, 181, 175, 169, 182, 177, 180, 171])
pd.cut(s, 3, labels=['Small', 'Medium', 'Large'])  #create category, equal interval

#pivot table

In [ ]:
pd.pivot_table(df,index=["Manager","Rep"],values=["Price"],aggfunc=[np.sum,np.mean])
pd.pivot_table(df,index=["Manager","Rep"],values=["Price","Quantity"],columns=["Product"],aggfunc=[np.sum])
table= pd.pivot_table(df,index=["Manager","Status"],columns=["Product"],values=["Quantity","Price"],
               aggfunc={"Quantity":len,"Price":np.sum},fill_value=0)
table.query('Manager == ["Debra Henley"]') #filter
table.query('Status == ["pending","won"]')

In [50]:
random.randint(1,10,20)

TypeError: randint() takes 3 positional arguments but 4 were given

In [44]:
import random 

In [58]:
np.random.randint(10, 20, (4,2))

array([[12, 17],
       [18, 16],
       [19, 12],
       [16, 19]])

In [56]:
np.random.randint(-5, 0, 9)

array([-3, -2, -4, -1, -2, -3, -1, -4, -5])

In [60]:
df.iloc[:2]

Cost Item Purchased   Name
Store 1  22.5       Dog Food  Chris
Store 1   2.5   Kitty Litter  Kevyn

In [9]:
np.random.binomial(1,0.5,10)

array([1, 1, 1, 1, 0, 1, 1, 0, 0, 1])

#scipy

In [1]:
from scipy import stats